### ISSUE TITLE
Extension License

### ISSUE THREAD

**Issue by aYorky** [austenc/vscode-tailwind-docs#2]
HI,

I'd like to use this extension for work, but my company requires license information for the vetting process. What license is this extension under?

Thanks.

**Comment by austenc** [comment]
@aYorky great question!

I've added a license -- it's using the MIT license, simple and permissive. 

https://github.com/austenc/vscode-tailwind-docs/pull/3

Will be updating it for the latest version of Tailwind and tagging a release with these changes shortly.

**Comment by aYorky** [comment]
Thank you very much!

**Comment by austenc** [comment]
You're welcome! Just tagged the new version. Hope you find it useful!
